### ISSUE TITLE
[Suggestion]: Discoverability

### ISSUE THREAD

**Issue by p3lim** [Mrbysco/GeOre#2]
### General Info

- [X] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Geodes can be pretty hard to find, so I'd suggest adding a tool that'd aid in discovering them.

Something like a divining rod combined with the type of material that you'd want to find, that'd increasingly shake when you're facing and getting closer to a geode of its type. Or maybe something a bit more high-tech, redstone-esque style.

**Comment by ShyNieke** [comment]
the idea behind Ge-ores is that they are hard to find but once found rewarding, for the time being I will have to say no to adding this, if more people want this I can think about adding such feature.
