### ISSUE TITLE
[Suggestion]: Redstone Comparator detects buds

### ISSUE THREAD

**Issue by donmor** [Mrbysco/GeOre#4]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Put a Redstone Comparator in front of an air block aside a budding ore block. While a bud grows, the comarator produces increasing signal level (4/8/12/15).

**Comment by ShyNieke** [comment]
While it is an interesting idea, if I am remembering correctly vanilla buds don't have this behavior, since we want to stay true to how the vanilla amethysts work I don't think we will implement this feature. I can't speak for in the future though
